$('.owl-carousel').owlCarousel({
    loop:true,
    margin:11,
    nav:false,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:4
        },
        1000:{
            items:6
        }
    }
})